logging.level.guru=debug
server.port=8082

#defaults for this image vromero/activemq-artemis-docker
spring.artemis.user=artemis
spring.artemis.password=simetraehcapa

logging.level.com.springframework=debug